// swift-tools-version:5.7

import PackageDescription

// Do not edit this file, this is here so it does not show in Xcode.
let package = Package(
  name: "swift-tca-loadable-examples",
  products: [
  ],
  dependencies: [
  ],
  targets: [
  ]
)
