name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ['14.2']
        config: ['debug', 'release']
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Swift Version
        run: swift --version
      - name: Run ${{ matrix.xcode }} Tests
        run: make CONFIG=${{ matrix.config }} test-library

