name: CI

on:
  push:
    branches:
      - main 
      - develop
    pull_request:
      branches:
          - '*'

jobs:
  build:
    name: MacOS
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: Run swift tests
      run: make test-swift
