name: Format

on:
  push:
    branches:
      - main

jobs:
  swift_format:
    name: swift-format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Swift Format
        run: brew install swift-format
      - name: Run swift-format.
        run: make format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run swift-format
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
